name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          ls -A
          pwd
          git config --global user.name 'mirsella'
          git config --global user.email 'mirsella@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git remote add clone https://github.com/mirsella/lacgtcosmeva.github.io
          git push -f clone master
